config/routes.rb
Rails.application.routes.draw do
  
  root 'products#index'
  resources :orders
  resources :carts
  get '/carts' => 'carts#index'
  get '/carts/:id' => 'carts#add'
  resources :products
  resources :categories
  devise_for :users

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	  where("info LIKE ?", "%#{search}%")
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order(params[:sort])
    @categories = Category.all

    if params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
    else
      @products = Product.all.order('created_at DESC')
    end
    
  end

  # GET /products/1
  # GET /products/1.json
  #show only one
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :category_id, :amount, :info)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
 <div class="form-products">
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="input-group ">
    <span class="input-group-addon" id="basic-addon1"><%= f.label :name %></span>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Name" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon" id="basic-addon1">$</span>
    <%= f.number_field :price, :class => "form-control", :placeholder => "Price" %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%# f.number_field :category_id %>
    <select class="form-control" id="sel1">
    <% @categories = Category.all %>
    <%= @categories.each do |cat| %>
        <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
      </select>
  </div>
  <div class="input-group">
    <%# f.label :amount %><br>
    <%# f.number_field :amount %>
  </div>
  <div class="form-group">
    <%= f.text_area :info, :class => "form-control", placeholder: "Info", rows:  "8"  %>
  </div>
  <div class="actions">
    <%= f.submit nil , :class => "btn btn-success" %>
    <%= link_to 'Back', products_path, :class => "btn btn-default" %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    
    <h1>Listing Products</h1>
    <%= link_to 'New Product', new_product_path, :class => "btn btn-primary" %>

<table>
  <thead>
    <tr>
    <th>ID</th>
      <th class="tableThName"><%= link_to 'Name',:sort => 'name' %></th>
      <th><%= link_to 'Price',:sort => 'price'%></th>
      <th><%= link_to 'Category',:sort => 'category_id'%></th>
      <th>Info</th>
      <th><%= link_to 'Created at',:sort => 'created_at'%></th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each  do |product| %>
      <tr>
       <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td><%= sprintf("$%0.02f", product.price) %></td>
        <td> <%= @categories.find(product.category_id).name %></td>
        <td><%# product.amount %></td>
        <td><%= product.info %></td>
        <td><%= time_ago_in_words(product.created_at) %></td>
       
        <td><%# button_to 'Add', carts_path(:product_id => product.id), :class => "btn btn-info" %>
          <%# button_to 'Add',:action => :create,
                              :controler => :carts,
                              :id => product.id
                              #:class => "btn btn-info"
                               %>
                               <a href="/carts/<%= product.id %>"> Add</a>
        </td>
        <td><%= link_to 'Show', product, :class => "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_product_path(product),:class => "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger" %></td>
      </tr>
      <br>
    <% end %>
  </tbody>
</table>
</div>
</div>

<br>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
<h1>New Product</h1>

<%= render 'form' %>


</div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
   <div class="show-products"> 
		<p>
		  <strong>Name:</strong>
		  <%= @product.name %>
		</p>

		<p>
		  <strong>Price:</strong>
		  <%= sprintf("$%0.02f", @product.price) %>
		</p>

		<p>
		  <strong>Category:</strong>
		  <%= Category.find(@product.category_id).name %>
		</p>

		<p>
		  <strong>Info:</strong>
		  <%= @product.info %>
		</p>

		<%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-warning"%> |
		<%= link_to 'Back', products_path,:class => "btn btn-default" %>
	</div>
	</div>
</div>